---
apiVersion: v1
kind: List
items:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: message-service
      namespace: config-examples
      labels:
        spring.cloud.kubernetes.config: "true"
    data:
      message: "Value from K8s config"
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: demo-configmap
      namespace: config-examples
    data:
      foo: "foo value"
      bar: "bar value"



